import "../styles/globals.scss";
import s from "@/styles/layout.module.scss"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className={s.navbar}>
        <div className={s.flex_box}>
          <div className={s.flex_item} id={s.flex_name}>
            <h1 title="Hello???"><a href="/">Anthony Ciocco</a></h1>
          </div>
          <div className={s.flex_item} id={s.flex_nav}>
            <h3><a href="/">Home</a></h3>
          </div>
          <div className={s.flex_item} id={s.flex_nav}>
            <h3 title="Coming soon...">[Antdocs]</h3>
          </div>
        </div>
      </div>
      {children}
      </body>
    </html>
  )
}
